### ISSUE TITLE
Install with Homebrew

### ISSUE THREAD

**Issue by bartekpacia** [maciejzj/ssb#2]
[I created a Homebrew Formula](https://github.com/bartekpacia/homebrew-tools/blob/master/Formula/ssb.rb) for `ssb` to make the setup easier for me.

1. `brew tap bartekpacia/tools`
2. `brew install ssb`

or simply `brew install bartekpacia/tools/ssb`

Maybe someone finds it useful.

**Comment by maciejzj** [comment]
Thanks, this feels very gratifying 😊

I will add an info about home-brew installation to the README.

I believe it would be nice to add `pandoc` as optional (but default) dependency to the formulae.

I am not very familiar with ruby and formulae format, but I guess it would be something like here: https://docs.brew.sh/Formula-Cookbook#adding-optional-steps

```
option "without-pandoc", "Don't install pandoc (default markdown renderer)"
```

I won't make any PRs to your personal configs, to reduce the noise. It's up to you to follow this suggestion if you want.

**Comment by bartekpacia** [comment]
That's a good idea, thanks:)

Will do it soon™

**Comment by maciejzj** [comment]
I've implemented a major quality revamp throughout the whole program and created a homebrew tap dedicated to ssb (to reduce communication hustle during releases).

Thanks for the idea of using homebrew, I've acknowledged your support in the README :)
